from .agenda import *
from .aux_admin import *
from .cita_medica import *
from .consultorio import *
from .departamento import *
from .especialidad import *
from .estado_cita import *
from .grupo_ingresos import * 
from .lugar_atencion import * 
from .medico import *
from .paciente import *
from .usuario import * 
