# Generated by Django 5.2.3 on 2025-06-24 00:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_ips_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultorio',
            name='num_habitacion',
            field=models.PositiveIntegerField(unique=True, verbose_name='Número de habitación'),
        ),
        migrations.AlterField(
            model_name='grupoingresos',
            name='nivel_ingresos',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('NA', 'No Aplica')], max_length=5, verbose_name='Grupo de ingresos'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipo_regimen',
            field=models.CharField(choices=[('CONTR', 'Contributivo'), ('SUB', 'Subsidiado'), ('N/A', 'No aplica')], max_length=20, verbose_name='Tipo de regimen'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='documento',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='El número de documento no es válido', regex='^\\d{4,10}')], verbose_name='Número de documento'),
        ),
    ]
