# Generated by Django 5.2.3 on 2025-07-02 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_ips_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='lugar_atencion',
            field=models.ForeignKey(blank=True, default='Asistir Salud LTDA', null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyecto_ips_app.lugaratencion'),
        ),
    ]
